name: ci
on:
  push:
    branches: [ v1-dev, master ]
  pull_request:
    branches: [ v1-dev, master ]
jobs:
  build_rocket:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          sudo apt install -y clang llvm doxygen flex bison libfl-dev ccache
      - name: Untar linux.bin
        run: |
          git submodule set-url ready-to-run https://github.com/jaypiper/gsim-ready-to-run.git
          make init
      - name: Compile
        run: |
          make compile dutName=rocket -j `nproc`
      - name: Build EMU
        run: |
          make difftest MODE=0 dutName=rocket -j `nproc`
